# Generated by Django 3.2.4 on 2021-07-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_due_created_todolist_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='categories',
            new_name='category',
        ),
    ]
